GoodMedicalApp/Controllers/RoomController.cs
using GoodMedicalApp.BusinessServices.Services;
using GoodMedicalApp.BusinessServices.Services.Implementation;
using GoodMedicalApp.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoodMedicalApp.Controllers
{
    public class RoomController : Controller
    {
        public RoomController()
        {
            roomService = new RoomService();
        }

        private readonly IRoomService roomService;

        // GET: Patient
        public ActionResult Index()
        {
            var rooms = roomService.GetAll();
            if (rooms != null && rooms.Any())
            {
                return View(rooms);
            }
            else
            {
                return Content("<p>The list of rooms is empty<p>");
            }
        }

        public ActionResult FormRoom()
        {
            return View();
        }

        [HttpPost]
        public ContentResult CreateRoom(Room room)
        {
            roomService.Add(room);
            roomService.Save();
            return Content("<p>The room was created successfully!</p>");
        }

        public ContentResult Remove(int id)
        {
            var room = roomService.GetItemById(id);
            if (room != null)
            {
                roomService.Remove(room);
                roomService.Save();
                return Content("<p>The room was removed successfully!</p>");
            }
            else
            {
                return Content("<p>The room wasn't found!</p>");
            }
        }

        public ActionResult FormUpdate(int id)
        {
            var room = roomService.GetItemById(id);
            if (room != null)
            {
                return View(room);
            }
            else
            {
                return Content("<p>The room wasn't found!</p>");
            }
        }

        [HttpPost]
        public ContentResult Update(Room room)
        {
            roomService.Update(room);
            roomService.Save();
            return Content("<p>The room was updated successfully!</p>");
        }

    }
}

GoodMedicalApp/Views/Room/FormRoom.cshtml
@model GoodMedicalApp.Domain.Models.Room
@using (Html.BeginForm("CreateRoom", "Room", FormMethod.Post))
{
    <p>@Html.LabelFor(x => x.Number)</p>
    <p>@Html.TextBoxFor(x => x.Number, "Number")</p>
    <p><input type="submit" value="Send" /></p>
}

GoodMedicalApp/Views/Room/FormUpdate.cshtml
@model GoodMedicalApp.Domain.Models.Room
@using (Html.BeginForm("Update", "Room", FormMethod.Post))
{
    <p>Current room's number is <b>@Model.Number</b></p>
    <p>@Html.HiddenFor(x => x.Id)</p>
    <p>@Html.LabelFor(x => x.Number)</p>
    <p>@Html.TextBoxFor(x => x.Number)</p>
    <p><input type="submit" value="Send" /></p>
}

GoodMedicalApp/Views/Room/Index.cshtml
@using GoodMedicalApp.Domain.Models
@model IList<Room>

<table border="1">
        <caption>Rooms</caption>
    <tr>
        <th>Id</th>
        <th>Number of room</th>
        <th colspan="2">Actions</th>
    </tr>
    @foreach (var entity in Model)
    {
        <tr>
            <td>@entity.Id</td>
            <td>@entity.Number</td>
            <td>@Html.ActionLink("Remove", "Remove", "Room", new { id = entity.Id }, null)</td>
            <td>@Html.ActionLink("Edit", "FormUpdate", "Room", new { id = entity.Id }, null)</td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Add room", "FormRoom", "Room")
</div>