GoodMedicalApp/Controllers/DoctorController.cs
using GoodMedicalApp.BusinessServices.Services;
using GoodMedicalApp.BusinessServices.Services.Implementation;
using GoodMedicalApp.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace GoodMedicalApp.Controllers
{
    public class DoctorController : Controller
    {
        public DoctorController()
        {
            doctorService = new DoctorService();
        }

        private readonly IDoctorService doctorService;

        // GET: Doctor
        public ActionResult Index()
        {
            var doctors = doctorService.GetAll();
            return View(doctors);
        }

        public ActionResult FormDoctor()
        {
            return View();
        }

        [HttpPost]
        public ContentResult CreateDoctor(Doctor doctor)
        {
            doctorService.Add(doctor);
            doctorService.Save();
            return Content("<p>The doctor was created successfully!</p>");
        }

        public ContentResult Remove(int id)
        {
            var doctor = doctorService.GetItemById(id);
            if (doctor != null)
            {
                doctorService.Remove(doctor);
                doctorService.Save();
                return Content("<p>The doctor was removed successfully!</p>");
            }
            else
            {
                return Content("<p>The doctor wasn't found!</p>");
            }
        }

        public ActionResult FormUpdate(int id)
        {
            var doctor = doctorService.GetItemById(id);
            if (doctor != null)
            {
                return View(doctor);
            }
            else
            {
                return Content("<p>The doctor wasn't found!</p>");
            }
        }

        [HttpPost]
        public ContentResult Update(Doctor doctor)
        {
            doctorService.Update(doctor);
            doctorService.Save();
            return Content("<p>The doctor was updated successfully!</p>");
        }
    }
}

GoodMedicalApp/Views/Doctor/FormDoctor.cshtml
@model GoodMedicalApp.Domain.Models.Doctor
@using (Html.BeginForm("CreateDoctor", "Doctor", FormMethod.Post))
{
    <p>@Html.LabelFor(x => x.FirstName)</p>
    <p>@Html.TextBoxFor(x => x.FirstName, "Name")</p>
    <p>@Html.LabelFor(x => x.LastName)</p>
    <p>@Html.TextBoxFor(x => x.LastName, "Last Name")</p>
    <p>@Html.LabelFor(x => x.Qualification)</p>
    <p>@Html.TextBoxFor(x => x.Qualification,"Qualification")</p>
    <p><input type="submit" value="Send" /></p>
}

GoodMedicalApp/Views/Doctor/FormUpdate.cshtml
@model GoodMedicalApp.Domain.Models.Doctor
@using (Html.BeginForm("Update", "Doctor", FormMethod.Post))
{   
    <p>@Html.HiddenFor(x => x.Id)</p>
    <p>Current doctor's firstname is <b>@Model.FirstName</b></p>
    <p>@Html.TextBoxFor(x => x.FirstName)</p>
    <p>Current doctor's lastname is <b>@Model.LastName</b></p>
    <p>@Html.TextBoxFor(x => x.LastName)</p>
    <p>Current doctor's qualification is <b>@Model.Qualification</b></p>
    <p>@Html.TextBoxFor(x => x.Qualification)</p>
    <p><input type="submit" value="Send" /></p>
}

GoodMedicalApp/Views/Doctor/Index.cshtml
@using GoodMedicalApp.Domain.Models
@model IList<Doctor>

<table border="1">
    <caption>
        Doctors
    </caption>
    <tr>
        <th>Id</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Qualification</th> 
        <th colspan="2">Actions</th>       
    </tr>
    @foreach (var entity in Model)
    {
        <tr>
            <td>@entity.Id</td>
            <td>@entity.FirstName</td>
            <td>@entity.LastName</td>
            <td>@entity.Qualification</td>
            <td>@Html.ActionLink("Remove", "Remove", "Doctor", new { id = entity.Id }, null)</td>
            <td>@Html.ActionLink("Edit", "FormUpdate", "Doctor", new { id = entity.Id }, null)</td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Add doctor", "FormDoctor", "Doctor")
</div>