GoodMedicalApp/Controllers/OperationController.cs
using GoodMedicalApp.BusinessServices.Services;
using GoodMedicalApp.BusinessServices.Services.Implementation;
using GoodMedicalApp.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoodMedicalApp.Controllers
{
    public class OperationController : Controller
    {
        public OperationController()
        {
            operationService = new OperationService();
            treatmentService = new TreatmentService();
            typeOperationService = new TypeOperationService();
            medicineService = new MedicineService();
        }

        private readonly IOperationService operationService;
        private readonly ITreatmentService treatmentService;
        private readonly ITypeOperationService typeOperationService;
        private readonly IMedicineService medicineService;

        // GET: Operation
        public ActionResult Index()
        {

            var operations = operationService.GetAll();
            return View(operations);
        }

        public ActionResult FormOperation()
        {
            var treatments = treatmentService.GetAll();
            var typeOperations = typeOperationService.GetAll();
            var medicines = medicineService.GetAll();

            var selectListTreatments = new SelectList(treatments, "Id", "Id");
            var selectListTypeOperations = new SelectList(typeOperations, "Id", "Name", "Name");

            ViewBag.treatments = selectListTreatments;
            ViewBag.typeOperations = selectListTypeOperations;
            ViewBag.medicines = medicines;

            return View(new OperationTransfer());
        }

        public ContentResult CreateOperation(OperationTransfer operationTransfer)
        {
            var operation = new Operation();
            operation.CurrentTypeOperation = new TypeOperation() { Id = operationTransfer.CurrentTypeOperation.Id };
            operation.TreatmentId = operationTransfer.TreatmentId;
            if (operationTransfer.Medicines.Any())
            {
                operation.Medicines = new List<Medicine>();
                foreach (var id in operationTransfer.Medicines)
                {
                    var medicine = medicineService.GetItemById(id);
                    operation.Medicines.Add(medicine);
                }
            }

            operationService.Add(operation);
            operationService.Save();
            return Content("<p>The operation was created successfully!</p>");
        }

        public ContentResult Remove(int id)
        {
            var operation = operationService.GetItemById(id);
            if (operation != null)
            {
                operationService.Remove(operation);
                operationService.Save();
                return Content("<p>The operation was removed successfully!</p>");
            }
            else
            {
                return Content("<p>The operation wasn't found!</p>");
            }

        }

        public ActionResult FormUpdate(int id)
        {
            try
            {
                var operationTransfer = operationService.GetTransferItemById(id);

                var treatments = treatmentService.GetAll();
                var typeOperations = typeOperationService.GetAll();
                var medicines = medicineService.GetAll();

                var selectListTreatments = new SelectList(treatments, "Id", "Id");
                var selectListTypeOperations = new SelectList(typeOperations, "Id", "Name", "Name");

                ViewBag.treatments = selectListTreatments;
                ViewBag.typeOperations = selectListTypeOperations;
                ViewBag.medicines = medicines;

                return View(operationTransfer);
            }
            catch (ArgumentException e)
            {
                return Content($"<p>{e.Message}</p>");
            }
            catch (Exception e)
            {
                return Content($"<p>{e.Message}</p>");
            }
        }

        [HttpPost]
        public ContentResult Update(OperationTransfer operationTransfer)
        {
            try
            {
                var operation = operationService.GetItemFromTransferItem(operationTransfer);

                operationService.Update(operation);
                operationService.Save();

                return Content("<p>The operation was updated successfully!</p>");
            }
            catch (ArgumentException e)
            {
                return Content($"<p>The operation wasn't updated! {e.Message}</p>");
            }
            catch (Exception e)
            {
                return Content($"<p>{e.Message}</p>");
            }
        }

    }
}

GoodMedicalApp/Views/Operation/FormOperation.cshtml
@model GoodMedicalApp.Domain.Models.OperationTransfer
@using (Html.BeginForm("CreateOperation", "Operation", FormMethod.Post))
{
    <p>@Html.LabelFor(x => x.TreatmentId, "Treatment's Id")</p>
    <p>@Html.DropDownListFor(x => x.TreatmentId, ViewBag.treatments as SelectList)</p>
    <p>@Html.LabelFor(x => x.CurrentTypeOperation.Id, "Operation's type")</p>
    <p>@Html.DropDownListFor(x => x.CurrentTypeOperation.Id, ViewBag.typeOperations as SelectList)</p>
    <p>@Html.LabelFor(x => x.Medicines)</p>
    <p>@Html.ListBoxFor(x => x.Medicines, new MultiSelectList(ViewBag.medicines, "Id", "Name"))</p>
    <p><input type="submit" value="Send" /></p>
}

GoodMedicalApp/Views/Operation/FormUpdate.cshtml
@model GoodMedicalApp.Domain.Models.OperationTransfer
@using (Html.BeginForm("Update", "Operation", FormMethod.Post))
{
    <p>@Html.HiddenFor(x => x.Id)</p>
    <p>Current treatment <b>@Model.TreatmentId</b></p>
    <p>@Html.LabelFor(x => x.TreatmentId, "Treatment's Id")</p>
    <p>@Html.DropDownListFor(x => x.TreatmentId, ViewBag.treatments as SelectList)</p>

    <p>Current operation's type <b>@Model.CurrentTypeOperation.Name</b></p>
    <p>@Html.LabelFor(x => x.CurrentTypeOperation.Id, "Operation's type")</p>
    <p>@Html.DropDownListFor(x => x.CurrentTypeOperation.Id, ViewBag.typeOperations as SelectList)</p>

    if (Model.Medicines != null)
    {        
        <ul>
            @foreach (var medicine in Model.Medicines)
            {
                <li>@medicine</li>
            }
        </ul>
    }
    <p>@Html.LabelFor(x => x.Medicines)</p>
    <p>@Html.ListBoxFor(x => x.Medicines, new MultiSelectList(ViewBag.medicines, "Id", "Name"))</p>
    <p><input type="submit" value="Send" /></p>
}

GoodMedicalApp/Views/Operation/Index.cshtml
@using GoodMedicalApp.Domain.Models
@model IList<Operation>

<table border="1">
    <caption>Operations</caption>
    <tr>
        <th>Id</th>
        <th>Treatment Id</th>
        <th>Operation's type</th>
        <th>Medicines</th>
        <th colspan="2">Actions</th>
    </tr>
    @foreach (var entity in Model)
    {
        <tr>
            <td>@entity.Id</td>
            <td>@entity.TreatmentId</td>
            <td>@entity.CurrentTypeOperation.Name</td>
            <td>
                @if (entity.Medicines != null && entity.Medicines.Any())
                {
                    <ul>
                        @foreach (var medicine in entity.Medicines)
                        {
                            <li>@medicine.Name</li>
                        }
                    </ul>
                }
            </td>
            <td>@Html.ActionLink("Remove", "Remove", "Operation", new { id = entity.Id }, null)</td>
            <td>@Html.ActionLink("Edit", "FormUpdate", "Operation", new { id = entity.Id }, null)</td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Add operation", "FormOperation", "Operation")
</div>