GoodMedicalApp/Controllers/TypeOperationController.cs
using GoodMedicalApp.BusinessServices.Services;
using GoodMedicalApp.BusinessServices.Services.Implementation;
using GoodMedicalApp.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoodMedicalApp.Controllers
{
    public class TypeOperationController : Controller
    {
        public TypeOperationController()
        {
            typeOperationService = new TypeOperationService();
        }

        private readonly ITypeOperationService typeOperationService;

        // GET: TypeOperation
        public ActionResult Index()
        {
            var typeOperations = typeOperationService.GetAll();
            return View(typeOperations);
        }

        public ActionResult FormTypeOperation()
        {
            return View();
        }

        [HttpPost]
        public ContentResult CreateTypeOperation(TypeOperation typeOperation)
        {
            typeOperationService.Add(typeOperation);
            typeOperationService.Save();
            return Content("<p>The operation's type was created successfully!</p>");
        }

        public ContentResult Remove(int id)
        {
            var typeOperation = typeOperationService.GetItemById(id);
            if (typeOperation != null)
            {
                typeOperationService.Remove(typeOperation);
                typeOperationService.Save();
                return Content("<p>The operation's type was removed successfully!</p>");
            }
            else
            {
                return Content("<p>The operation's type wasn't found!</p>");
            }
        }

        public ActionResult FormUpdate(int id)
        {
            var typeOperation = typeOperationService.GetItemById(id);
            if (typeOperation != null)
            {
                return View(typeOperation);
            }
            else
            {
                return Content("<p>The operation's type wasn't found!</p>");
            }
        }

        [HttpPost]
        public ContentResult Update(TypeOperation typeOperation)
        {
            typeOperationService.Update(typeOperation);
            typeOperationService.Save();
            return Content("<p>The operation's type was created successfully!</p>");
        }
    }
}

GoodMedicalApp/Views/TypeOperation/FormTypeOperation.cshtml
@model GoodMedicalApp.Domain.Models.TypeOperation
@using (Html.BeginForm("CreateTypeOperation", "TypeOperation", FormMethod.Post))
{
    <p>@Html.LabelFor(x => x.Name)</p>
    <p>@Html.TextBoxFor(x => x.Name, "Name")</p>
    <p><input type="submit" value="Send" /></p>
}

GoodMedicalApp/Views/TypeOperation/FormUpdate.cshtml
@model GoodMedicalApp.Domain.Models.TypeOperation
@using (Html.BeginForm("Update", "TypeOperation", FormMethod.Post))
{
    <p>Current type's name is <b>@Model.Name</b></p>
    <p>@Html.HiddenFor(x => x.Id)</p>
    <p>@Html.LabelFor(x => x.Name)</p>
    <p>@Html.TextBoxFor(x => x.Name)</p>
    <p><input type="submit" value="Send" /></p>
}

GoodMedicalApp/Views/TypeOperation/Index.cshtml
@using GoodMedicalApp.Domain.Models
@model IList<TypeOperation>

<table border="1">
    <caption>Types of Operations</caption>
    <tr>
        <th>Id</th>
        <th>Name of the type</th>
        <th colspan="2">Actions</th>
    </tr>
    @foreach (var entity in Model)
    {
        <tr>
            <td>@entity.Id</td>
            <td>@entity.Name</td>
            <td>@Html.ActionLink("Remove", "Remove", "TypeOperation", new { id = entity.Id }, null)</td>
            <td>@Html.ActionLink("Edit", "FormUpdate", "TypeOperation", new { id = entity.Id }, null)</td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Add operation's type", "FormTypeOperation", "TypeOperation")
</div>